version: 2
updates:
  - package-ecosystem: pip
    directory: /flask
    commit-message:
      prefix: Flask
    labels:
      - dependencies
    assignees:
      - kevinlul
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /react
    commit-message:
      prefix: React
    labels:
      - dependencies
    assignees:
      - kevinlul
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    commit-message:
      prefix: Docker
    labels:
      - dependencies
    assignees:
      - kevinlul
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: CI
    labels:
      - dependencies
    assignees:
      - kevinlul
    schedule:
      interval: weekly
